### PR TITLE
doc(init): added org-wide health files

### PR DESCRIPTION
**Pull request by 4w3Official**
## Proposed changes

organization-wide PR template

## Types of changes

What types of changes does your code introduce to Scuffle?
_Put an `x` in the boxes that apply_

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] Documentation Update (if none of the other choices apply)

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._

- [x] I have read the [CONTRIBUTING](https://github.com/ScuffleTV/scuffle/blob/main/CONTRIBUTING.md) doc
- [x] Lint and unit tests pass locally with my changes
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have added necessary documentation (if appropriate)
- [x] Any dependent changes have been merged and published in downstream modules

## Further comments

-/-

### CODE REVIEW

**Comment by TroyKomodo** [comment]
Does this work?

**Comment by 4w3Official** [comment]
Yes. [github.blog/changelog/2019-02-21-organization-wide-community-health-files](https://github.blog/changelog/2019-02-21-organization-wide-community-health-files/)

**Comment by TroyKomodo** [comment]
Neat, can you add a security template too?

**Comment by TroyKomodo** [comment]
Also, Codeowners.

```
* @ScuffleTV/maintainers 
```

**Comment by 4w3Official** [comment]
ready

**Review by TroyKomodo — APPROVED** [review]
Lgtm

**Pull request merged**
